site_name: Fading Suns
nav:
    - Home: 'index.md'
    - 'Maailma':    
        - 'Yleiskuvaus': 'maailma.md'
        - 'Tunnetut planeetat': 'planeetat.md'
    - 'Rhojamar':
        - 'Gazinin Aapinen': 'GhazinAapinen.md'
        - 'Ghazin Gazette 1': 'GhazinGazette1.md'
        - 'Ghazin Gazette 2': 'GhazinGazette2.md'
        - 'Maamiehen tietolaari 915': 'RurMaamiehenTietolaari.md'
    - Säännöt: 'saannot.md'
    - Hahmonluonti: 'hahmot.md'
    - Kampanja: 'kampanja.md'
    - 'Kaudet':
        - 'Ensimmäinen kausi: ryöstö': 'kausi1'
        - 'Toinen kausi: vieraita avaruudesta': 'kausi2'
        - 'Kolmas kausi: paikallispolitiikkaa': 'kausi3'
theme: material