site_name: Fading Suns
nav:
    - Home: 'index.md'
    - 'Maailma':    
        - 'Yleiskuvaus': 'maailma.md'
        - 'Tunnetut planeetat': 'planeetat.md'
    - Säännöt: 'saannot.md'
    - Hahmonluonti: 'hahmot.md'
    - Kampanja: 'kampanja.md'
    - 'Kaudet':
        - 'Ensimmäinen kausi: ryöstö': 'kausi1'
        - 'Toinen kausi: vieraita avaruudesta': 'kausi2'
theme: material